name: Caller workflow
on:
 workflow_dispatch:

jobs:
  caller:
    strategy:
      matrix:
        msg: [Once, Twice, Thrice]  
    uses: sathish-sign/github-wf/.github/workflows/reusable.yml@main
    with:
      msg: "Called from caller workflow ${{ matrix.msg }}"
  
